### ISSUE TITLE
PCB review

### ISSUE THREAD

**Issue by gkasprow** [elhep/CPCIS-AC-PSU#1]
@tprzywoz there are a few issues
- [x] the clearance for AC traces and pads must be at least 2mm from any other objects on secondary side (DC) and at least 1mm from all objects on primary side (AC). The best is just to assign 2mm rule for all AC nets. This affects AC_N, AC_L , J5 and J7

**Comment by jordens** [comment]
Could you post PDFs to releases (for this and DC as well) so we can have a look without altium?

**Comment by gkasprow** [comment]
done

**Comment by tprzywoz** [comment]
Added clearance top rule AC to all 2mm and Power Plane Clearance AC to all 2mm.

**Comment by filipswit** [comment]
There are few more issues:

- [x] dangling piece of copper
![image](https://user-images.githubusercontent.com/24258965/100549351-c81df880-3272-11eb-9d33-4e74f2025954.png)

- [x] align this trace 
![image](https://user-images.githubusercontent.com/24258965/100549366-e126a980-3272-11eb-86ad-5eed567bb58f.png)

- [x] L3, remove the copper between AC connectors 
![image](https://user-images.githubusercontent.com/24258965/100549390-fef40e80-3272-11eb-8dc1-4213d841cbbd.png)
